import subprocess

# List of titles
titles = [
"silo",
"The Fall of the House of Usher",
"gen V",
"Shrinking",
"Blue Eye Samurai",
"Sapne Vs Everyone",
"The Diplomat",
"Chamak",
"Poker Face",
"Jury Duty",
"silo",
"All the Light We Cannot See",
"beckham",
"Lessons in Chemistry",
"The Crowded Room",
"Painkiller",
"Dear Child",
"Twisted Metal",
"A Murder at the End of the World",
"Arnold",
"The Railway Men",
"Rabbit Hole",
"Wednesday",
"The Sandman",
"1899",
"Black Bird",
"The Peripheral",
"Cyberpunk: Edgerunners",
"The Lincoln Lawyer",
"Archive 81",
"Vikings: Valhalla",
"Guillermo del Toro's Cabinet of Curiosities",
"1923",
"Our Flag Means Death",
"NCR Days",
"The Summer I Turned Pretty",
"Pam & Tommy",
"the offer",
"The Gilded Age",
"Under the Banner of Heaven",
"Outer Range",
"the patient",
"the english",
"The Tourist",
"fallout",
" The Gentlemen",
"Ahsoka",
"Invincible",
"Only Murders in the Building",
"The Chestnut Man",
"The Innocent",
"baby reindeer",
"shogun",
"It's a Sin",
"Inside Job",
"Young Rock",
"The Undoing",

]

# Iterate over titles and run the command
for title in titles:
    command = ["python", "-m", "1337x", title + " s01"]
    subprocess.run(command)

