<Configuration>
  <MappedFolders>
    <MappedFolder>
      <HostFolder>C:\backup</HostFolder>
      <SandboxFolder>C:\backup</SandboxFolder>
      <ReadOnly>false</ReadOnly>
    </MappedFolder>
  </MappedFolders>
</Configuration>
