version: "3"
services:
  windows:
    image: dockurr/windows
    container_name: windowserver22
    environment:
      VERSION: "2022"
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8888:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 2m
    restart: on-failure
