---
- name: Update .bashrc on all linux hosts
  hosts: linux
  become: yes
  tasks:
    - name: Check if /root/.bashrc exists on the control node
      local_action:
        module: stat
        path: /root/.bashrc
      register: control_bashrc

    - name: Fail if /root/.bashrc does not exist on the control node
      fail:
        msg: "/root/.bashrc does not exist on the control node."
      when: not control_bashrc.stat.exists

    - name: Fetch /root/.bashrc from control node
      fetch:
        src: /root/.bashrc
        dest: /tmp/control_bashrc
        flat: yes
      delegate_to: localhost

    - name: Copy .bashrc to user home directories
      copy:
        src: /tmp/control_bashrc
        dest: ~/.bashrc
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0644'

    - name: Copy .bashrc to root directory
      copy:
        src: /tmp/control_bashrc
        dest: /root/.bashrc
        owner: root
        group: root
        mode: '0644'

    - name: Source ~/.bashrc for user
      shell: source ~/.bashrc
      ignore_errors: yes

    - name: Source /root/.bashrc for root
      shell: source /root/.bashrc
      become: yes
      ignore_errors: yes
