Question.create!([
  { content: "What is the command to list all files in a directory?", hint: "Think about the basic file operations command", correct_answer: "ls" },
  { content: "What command is used to display the current directory?", hint: "It's short for 'print working directory'", correct_answer: "pwd" },
  { content: "Which command is used to remove a file?", hint: "It's a short form of 'remove'", correct_answer: "rm" },
  { content: "How do you display the contents of a file?", hint: "Think about showing the contents", correct_answer: "cat" },
  { content: "Which command is used to change the directory?", hint: "It's short for 'change directory'", correct_answer: "cd" },
  { content: "What command shows the current user?", hint: "It's a simple user command", correct_answer: "whoami" },
  { content: "How do you find the path of a command?", hint: "Think about locating the command", correct_answer: "which" },
  { content: "Which command is used to search for a pattern in files?", hint: "It's a famous pattern search command", correct_answer: "grep" },
  { content: "How do you display the first few lines of a file?", hint: "Think about the start of the file", correct_answer: "head" },
  { content: "How do you display the last few lines of a file?", hint: "Think about the end of the file", correct_answer: "tail" }
])

Choice.create!([
  { content: "ls", question_id: 1 },
  { content: "dir", question_id: 1 },
  { content: "list", question_id: 1 },
  { content: "pwd", question_id: 2 },
  { content: "cd", question_id: 2 },
  { content: "echo $PWD", question_id: 2 },
  { content: "rm", question_id: 3 },
  { content: "delete", question_id: 3 },
  { content: "erase", question_id: 3 },
  { content: "cat", question_id: 4 },
  { content: "show", question_id: 4 },
  { content: "display", question_id: 4 },
  { content: "cd", question_id: 5 },
  { content: "chdir", question_id: 5 },
  { content: "goto", question_id: 5 },
  { content: "whoami", question_id: 6 },
  { content: "who", question_id: 6 },
  { content: "id", question_id: 6 },
  { content: "which", question_id: 7 },
  { content: "find", question_id: 7 },
  { content: "locate", question_id: 7 },
  { content: "grep", question_id: 8 },
  { content: "search", question_id: 8 },
  { content: "findstr", question_id: 8 },
  { content: "head", question_id: 9 },
  { content: "top", question_id: 9 },
  { content: "start", question_id: 9 },
  { content: "tail", question_id: 10 },
  { content: "end", question_id: 10 },
  { content: "bottom", question_id: 10 }
])
